### ISSUE TITLE
[FEATURE] Drop Table Location

### ISSUE THREAD

**Issue by TwinDragon** [Mimikkk/Mimikk-Cogs#1]
## Describe the New Feature
The drop table will show where the boat girls drop, what maps, chapters, etc... It's a lot of data to show, so not sure if a table could work or not.

This will be added to the individual shipgirls page, though accounting will be necessary for event-only girls, like Mutsu, Nagato, Bismarck, etc... As the maps for some of those girls could be like B2, D2, D3, etc... Then there's of course the research girls which don't need any other changes on them, and there are also construction-only girls like all the subs if I recall.

**Comment by Mimikkk** [comment]
It has been done, added a tab containing info about: Construction Time / Type, Event, Exchange and Map locations
